name: Node.js Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Get all history for version calculation
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'
          scope: '@dnvgl'
          cache: 'pnpm'
      - uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
      - run: pnpm version $GITVERSION_SEMVER --no-git-tag-version
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}